name: native_font
description: A plugin for lazy loading of native fonts.
version: 1.0.0
homepage: https://github.com/xuning0/native_font

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.xuning.native_font
        pluginClass: NativeFontPlugin
      ios:
        pluginClass: NativeFontPlugin
